### ISSUE TITLE
Migrate to termdash for ui

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#31]
In response to #30 migration to [termdash](https://github.com/mum4k/termdash) has to be taken up. 

To work on this issue:
- Development related to migration to `termdash` will be done on the `migrate` branch *only*. 
- While sending in a PR for the same, instead of "Fixes #Issue", mention "Part of #Issue" and reference this issue. 

### TODO:
- [ ] Overall visuals, displayed by the command `grofer`
- [ ] Per proc visuals, displayed by the command `grofer proc -p PID`
- [ ] Info about all procs, displayed by the command `grofer proc`

**Comment by Gituser143** [comment]
@MadhavJivrajani Okay so we've got a major issue here, termdash does not support floats for bar charts, just ints. We could implement a custom widget but that requires a lot of refactoring and once again will have to fix the 0,0,0,0 issue for `MemStats` chart in `grofer proc`. Another downside, there are no tables here!

**Comment by MadhavJivrajani** [comment]
![image](https://user-images.githubusercontent.com/12381034/89657798-47b24100-d8eb-11ea-88b1-6f3d57ec662b.png)
